# -*- coding: utf-8 -*-
"""Streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G7O1ifaPzmJb1rTOuUhYb5XNNdGeN72r
"""

pip install streamlit

import streamlit as st

def main():
    st.title('Welcome to Your Application')
    st.image('https://drive.google.com/uc?id=1f3qXUf9wnUCrpg9VbEB983ny2F3BOext', use_column_width=True)
    st.image('https://drive.google.com/uc?id=1GAhrqblAjfJn8uEr1N0IFx9Q3tynAe8f', use_column_width=True)

    username = st.text_input('Username')
    password = st.text_input('Password', type='password')

    if st.button('Sign In'):
        if username == 'your_username' and password == 'your_password':
            st.success('Logged in as {}'.format(username))
            # Redirect to another page or perform actions after login
        else:
            st.error('Invalid credentials')

if __name__ == '__main__':
    main()